#!/bin/sh

VIMDIR=.vim
REMOTE_HOST=""
REMOTE_USER=${USER}
DST_DIR=""
REMOTE=0
GET=0
GIT_UPDATE=0

usage () {
    echo "Args:"
    echo "-r: remote install"
    echo "-g: get setup (set otherwise)"
    echo "-d: remote dir"
    echo "-u: remote user"
    echo "-h: remote host"
    echo "-U git update"
    exit 1
}

while getopts "UHrgd:u:h:" o; do
    case "${o}" in
        r) REMOTE=1
            ;;
        g) GET=1
            ;;
        d) DST_DIR="${OPTARG}/"
            ;;
        u) REMOTE_USER="${OPTARG}"
            ;;
        h) REMOTE_HOST="${OPTARG}"
            ;;
        H) usage
            ;;
        U) GIT_UPDATE=1
            ;;
        *) usage
            ;;

    esac
done
shift $((OPTIND-1))

if [ ${GIT_UPDATE} -eq 1 ]; then
    git fetch --all && git pull
else 
    if [ "${GET}" -eq 1 ]; then
        if [ ${REMOTE} -eq 1 ]; then
            rm -fr ${PWD}/${VIMDIR}
            echo "Getting setup from ${REMOTE_USER}@${REMOTE_HOST}:"
            rsync -avzh ${REMOTE_USER}@${REMOTE_HOST}:${VIMDIR} .
        else
            echo "Getting local setup"
            rm -fr ${PWD}/${VIMDIR}
            cp -a ${HOME}/${VIMDIR} .
        fi
    else
        if [ ${REMOTE} -eq 1 ]; then
            echo "Full remote directory is: ${DST_DIR}"
            echo "Setting setup to ${REMOTE_USER}@${REMOTE_HOST}:${DST_DIR}${VIMDIR}"
            rsync -avzh ${VIMDIR} ${REMOTE_USER}@${REMOTE_HOST}:${DST_DIR}${VIMDIR}
        else
            echo "Full local directory is: ${DST_DIR}"
            echo "Setting local setup"
            rm -fr ${DST_DIR}${VIMDIR}
            cp -a ${VIMDIR} ${DST_DIR}${VIMDIR}
        fi
    fi
fi
