#!/bin/sh

REMOTE_HOST=""
REMOTE_USER=""
REMOTE_DIR=""
REMOTE=0
GET=0

VIMDIR=.vim
GVIMRC=.gvimrc

while getopts "rgd:u:h:" o; do
   case "${o}" in
      r) REMOTE=1
         ;;
      g) GET=1
         ;;
      d) REMOTE_DIR="${OPTARG}"
         ;;
      u) REMOTE_USER="${OPTARG}"
         ;;
      h) REMOTE_HOST="${OPTARG}"
         ;;
      *)
         ;;
         
    esac
 done
shift $((OPTIND-1))

if [ "${GET}" -eq 1 ]; then
   if [ ${REMOTE} -eq 1 ]; then
      echo "Getting setup from ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}"
      rsync -avzh ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}${VIMDIR} .
      rsync -avzh ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}${GVIMRC} .
   else
      echo "Getting local setup"
      cp -a ~/${VIMDIR} .
      cp -a ~/${GVIMRC} .
   fi
else
   if [ ${REMOTE} -eq 1 ]; then
      echo "Setting setup to ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}"
      rsync -avzh ${VIMDIR} ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}
      rsync -avzh ${GVIMRC} ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}
   else
      echo "Setting local setup"
      rm -fr ${HOME}/${GVIMRC} ${HOME}/${VIMDIR}
      cp -a ${VIMDIR} ${HOME}/
      cp -a ${GVIMRC} ${HOME}/
   fi
fi
