#!/bin/sh

VIMDIR=.vim
REMOTE_HOST=
REMOTE_USER=${USER}
REMOTE_DIR="" # assume remote home
DST_DIR=${HOME}
REMOTE=0
GET=0
GIT_UPDATE=0

usage () {
    echo "Args:"
    echo "-r: remote install"
    echo "-g: get setup (set otherwise)"
    echo "-d: remote dir"
    echo "-u: remote user"
    echo "-h: remote host"
    echo "-U git update"
    exit 1
}

while getopts "UHrgd:u:h:" o; do
    case "${o}" in
        r) REMOTE=1
            ;;
        g) GET=1
            ;;
        d) DST_DIR="${OPTARG}/"
            ;;
        u) REMOTE_USER="${OPTARG}"
            ;;
        h) REMOTE_HOST="${OPTARG}"
            ;;
        H) usage
            ;;
        U) GIT_UPDATE=1
            ;;
        *) usage
            ;;

    esac
done
shift $((OPTIND-1))

if [ ${GIT_UPDATE} -eq 1 ]; then
    git fetch --all && git pull
fi

if [ "${GET}" -eq 1 ]; then
    if [ ${REMOTE} -eq 1 ]; then
        rm -fr ${PWD}/${VIMDIR}
        echo "Getting setup from ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}"
        rsync -avzh ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR} .
    else
        echo "Getting local setup"
        rm -fr ${PWD}/${VIMDIR}
        cp -a ${HOME}/${VIMDIR} .
    fi
else
    if [ ${REMOTE} -eq 1 ]; then
        echo "Full remote directory is: $REMOTE_DIR"
        echo "Setting setup to ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}${VIMDIR}"
        rsync -avzh ${VIMDIR} ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}${VIMDIR}
    else
        echo "Full local directory is: ${DST_DIR}"
        echo "Setting local setup"
        cp -a ${VIMDIR} ${DST_DIR}
    fi
fi
